### ISSUE TITLE
Initialization code missing in nvim plugin?

### ISSUE THREAD

**Issue by aserowy** [luckasRanarison/tree-sitter-hypr#8]
Hi,

i installed the grammar and thought everything was working. Looking into the plugin, the grammar registration is missing and only the filetype handling is given. Thus, after the plugin is installed i must register the parser by hand.

Was there a reason to not include the parser_config extension?

Kind regards
Alexander

**Comment by luckasRanarison** [comment]
Hi!

The reason is quite embarrassing, the plugin wasn't there from the beginning and I just forgot to move the parser config logic there... 

PRs are welcome you want to fix it :)
